### ISSUE TITLE
500 error adding new products version 1.44.1.1

### ISSUE THREAD

**Issue by springerin** [mash2/cobby-magento2#5]
```
Next Exception: Report ID: webapi-5ab10213680f1; Message: Notice: Undefined index: product_id in /var/www/current/vendor/mash2/cobby-magento2/Model/Import/Product/UrlManagement.php on line 185 in /var/www/current/vendor/magento/framework/Webapi/ErrorProcessor.php:195
Stack trace:
#0 /var/www/current/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 /var/www/current/vendor/magento/module-webapi/Controller/Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 /var/www/current/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/current/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#4 /var/www/current/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /var/www/current/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#6 /var/www/current/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#7 {main} [] []
[2018-03-20 12:44:04] main.CRITICAL: Exception: Notice: Undefined index: product_id in /var/www/current/vendor/mash2/cobby-magento2/Model/Import/Product/UrlManagement.php on line 185 in /var/www/current/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/current/vendor/mash2/cobby-magento2/Model/Import/Product/UrlManagement.php(185): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/www/curren...', 185, Array)
#1 /var/www/current/vendor/mash2/cobby-magento2/Model/Import.php(208): Mash2\Cobby\Model\Import\Product\UrlManagement->import(Array)
#2 [internal function]: Mash2\Cobby\Model\Import->importProductUrls('{"10119":[{"sto...')
#3 /var/www/current/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#4 /var/www/current/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#5 /var/www/current/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /var/www/current/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#7 /var/www/current/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /var/www/current/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#9 /var/www/current/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#10 {main}

Next Exception: Report ID: webapi-5ab102140bf77; Message: Notice: Undefined index: product_id in /var/www/current/vendor/mash2/cobby-magento2/Model/Import/Product/UrlManagement.php on line 185 in /var/www/current/vendor/magento/framework/Webapi/ErrorProcessor.php:195
Stack trace:
#0 /var/www/current/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 /var/www/current/vendor/magento/module-webapi/Controller/Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 /var/www/current/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/current/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#4 /var/www/current/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /var/www/current/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#6 /var/www/current/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

```

**Comment by slavkodick** [comment]
could you post the request for reproducing the issue

**Comment by slavkodick** [comment]
did you save config after updating cobby?

**Comment by springerin** [comment]
Hi @slavkodick 
I don't have the post since I am adding products from excel/cobby so no idea what is the post sent to magento. I did save, but I will do again a test, cause I am not sure if I did the save before adding new products and get back to you on that
